import path from 'node:path';
import {readFile,writeFile,copyFile,mkdir,readdir} from 'node:fs/promises';
import {chromium} from 'playwright';
import {demo,root,url,browserExecutable,folders,run,ffmpeg,probe,json,delay,sourceFence} from './common.mjs';

await folders();
const browser=await chromium.launch({headless:true,executablePath:browserExecutable,args:['--enable-webgl','--ignore-gpu-blocklist','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
const errors=[],captures=[];
const requested=process.argv.find(a=>a.startsWith('--only='))?.slice(7);
const recaptureFrom=Number(process.argv.find(a=>a.startsWith('--from='))?.slice(7)||99);
const requestedHeroes=process.argv.find(a=>a.startsWith('--heroes='))?.slice(9).split(',');
let config={version:1,seed:4093,flowers:[{id:'rose',count:4,color:'#e886a3'},{id:'heart-bloom',count:3,color:'#dfa4d8'},{id:'peony',count:3,color:'#fff1dc'}],fillers:[{id:'babys-breath',count:3,color:'#b7c9ae'}],wrapper:{id:'heart-collar',color:'#e1bd94'},ribbon:{id:'heart-knot',color:'#b77ca8'},effects:['hearts'],palette:'sugar',size:1,spread:1,gift:{to:'',from:'',title:'',message:''},objects:[]};
const durations={'02':4,'03':7,'04':5,'05':6,'06':6,'07':8,'08':4,'09':6,'10':9,'11':9,'12':3,'13':7,'14':5};
const button=(p,name)=>p.getByRole('button',{name,exact:true});
const tab=(p,name)=>p.getByRole('tab',{name,exact:true});
async function click(p,l,hold=180){await l.scrollIntoViewIfNeeded();const b=await l.boundingBox();await p.mouse.move(b.x+b.width/2,b.y+b.height/2,{steps:3});await delay(80);await l.click();await delay(hold);}
async function drag(p,l,value,hold=180){await l.scrollIntoViewIfNeeded();const b=await l.boundingBox();const info=await l.evaluate(n=>({min:Number(n.min),max:Number(n.max),value:Number(n.value)}));const at=v=>b.x+8+(b.width-16)*(v-info.min)/(info.max-info.min);await p.mouse.move(at(info.value),b.y+b.height/2,{steps:2});await p.mouse.down();for(let k=1;k<=6;k++){await p.mouse.move(at(info.value+(value-info.value)*k/6),b.y+b.height/2);await delay(45);}await p.mouse.up();await delay(hold);}
async function init(p,c){await p.addInitScript(c=>{if(c)localStorage.setItem('petalpop.draft.v1',JSON.stringify(c));document.addEventListener('DOMContentLoaded',()=>{const dot=document.createElement('div');dot.id='ad-pointer';dot.style.cssText='position:fixed;z-index:2147483647;width:19px;height:19px;border:2px solid #92576f;border-radius:50%;background:#fff9;box-shadow:0 2px 8px #92576f44;pointer-events:none;left:-100px;top:-100px;transform:translate(-50%,-50%)';document.body.appendChild(dot);document.addEventListener('pointermove',e=>{dot.style.left=e.clientX+'px';dot.style.top=e.clientY+'px';});document.addEventListener('pointerdown',()=>{dot.style.background='#92576faa';dot.style.scale='1.45';});document.addEventListener('pointerup',()=>{dot.style.background='#fff9';dot.style.scale='1';});});},c);p.on('pageerror',e=>errors.push(e.message));}
async function ready(p){await p.locator('[data-testid=scene][data-ready=true]').waitFor({timeout:40000});await delay(350);}
async function saveConfig(p){await delay(160);const c=await p.evaluate(()=>JSON.parse(localStorage.getItem('petalpop.draft.v1')));if(c)config=c;}
async function phase(p,color){await p.evaluate(color=>{let n=document.querySelector('#capture-fence');if(!n){n=document.createElement('div');n.id='capture-fence';n.style.cssText='position:fixed;left:0;top:0;width:8px;height:8px;z-index:2147483647;pointer-events:none';document.body.append(n);}n.style.background=color;},color);await p.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));}
async function fence(file){return sourceFence(file);}
async function shot(id,prepare,actions,options={}){
  const checkpoint=path.join(demo,'.cache',`config-${id}.json`), media=path.join(demo,'public/media',`${id}.mp4`);
  if(!process.argv.includes('--force')&&requested!==id&&Number(id)<recaptureFrom){try{config=JSON.parse(await readFile(checkpoint,'utf8'));const r=JSON.parse(await readFile(path.join(demo,'.cache',`capture-${id}.json`),'utf8'));await readFile(media);captures.push(r);console.log(`Reuse ${id}`);return;}catch{}}
  const context=await browser.newContext({viewport:{width:1440,height:1040},recordVideo:{dir:path.join(demo,'recordings/raw'),size:{width:1440,height:1040}},reducedMotion:'no-preference',permissions:['clipboard-read','clipboard-write']});
  const p=await context.newPage();await init(p,config);await p.goto(options.giftUrl||url);await phase(p,'#000000');if(!options.giftUrl)await ready(p);if(prepare)await prepare(p);await delay(250);await phase(p,'#FFFFFF');const begin=Date.now();const marks=[];
  const mark=label=>marks.push({label,time:(Date.now()-begin)/1000});
  await actions(p,mark);await saveConfig(p);const elapsed=(Date.now()-begin)/1000;await delay(Math.max(0,(durations[id]||6)*1000-elapsed*1000));
  const ending=Date.now();await phase(p,'#FF0000');await delay(400);await p.screenshot({path:path.join(demo,'output/qa',`capture-${id}.png`)});const screenshotSeconds=(Date.now()-ending)/1000;const raw=p.video();await context.close();const source=await raw.path();const sync=await fence(source);const duration=sync.end-sync.start;const start=sync.start;
  const target=durations[id]||6;const speed=Math.max(1,duration/target);
  await run(ffmpeg,['-y','-v','error','-i',source,'-vf',`trim=start=${start}:end=${sync.end},setpts=(PTS-STARTPTS)/${speed},fps=30,tpad=stop_mode=clone:stop_duration=1`,'-t',String(target),'-an','-c:v','libx264','-preset','fast','-crf','17','-pix_fmt','yuv420p',media]);
  const record={id,rawSource:path.relative(demo,source).replaceAll('\\','/'),trimStart:start,sourceSeconds:duration,wallSeconds:(ending-begin)/1000,screenshotSeconds,outputSeconds:target,speed,marks,synchronization:'Recorded start/end marker; frame-accurate decoded trim'};captures.push(record);await json(`.cache/capture-${id}.json`,record);await json(`.cache/config-${id}.json`,config);console.log(`Captured ${id}: ${duration.toFixed(2)}s → ${target}s`);
}
try{
await shot('02',null,async p=>{await click(p,button(p,'Start with a preset'));await click(p,p.getByRole('button',{name:/^Sweetheart/}));await delay(600);});
await shot('03',null,async p=>{await click(p,button(p,'Select Tulip'),350);await click(p,button(p,'Add one Rose'),400);await click(p,button(p,'Add one Rose'),500);await click(p,button(p,'Add one Tulip'),350);});
await shot('04',async p=>{await tab(p,'Fillers').click();},async p=>{await click(p,button(p,'Select Eucalyptus'),350);await click(p,button(p,'Add one Eucalyptus'),250);await click(p,button(p,'Natural filler arrangement'),350);await click(p,button(p,'Stepped filler arrangement'),500);});
await shot('05',null,async p=>{await click(p,tab(p,'Wrap'));await click(p,button(p,'Select Double-Layer Cone'),350);await click(p,p.getByRole('checkbox',{name:'Show bottom stems'}),250);await click(p,p.getByRole('checkbox',{name:'Show bottom stems'}),200);await click(p,tab(p,'Ribbon'));await click(p,button(p,'Select Classic Bow'),300);await click(p,p.getByRole('button',{name:'Apply Sugar blush palette'}),300);});
await shot('06',async p=>{await tab(p,'Flowers').click();await button(p,'Arrange blooms').click();},async p=>{await click(p,button(p,'Natural dome arrangement'),300);await click(p,button(p,'Stepped bouquet arrangement'),300);await drag(p,p.getByRole('slider',{name:'All flower height',exact:true}),.35);await drag(p,p.getByRole('slider',{name:'All flower size',exact:true}),1.1);await drag(p,p.getByRole('slider',{name:'All flower spread',exact:true}),1.12);});
await shot('07',async p=>{await tab(p,'Flowers').click();await button(p,'Arrange blooms').click();},async p=>{await click(p,button(p,'One bloom'),150);const points=await p.evaluate(()=>window.__petalpopFlowerPoints());const scene=await p.locator('.scene-wrap').boundingBox();const candidates=Object.entries(points).filter(([key,v])=>key.includes('rose')&&v[0]>scene.width*.25&&v[0]<scene.width*.75).sort((a,b)=>b[1][1]-a[1][1]);const selected=candidates[0]||Object.entries(points)[0];await p.mouse.click(scene.x+selected[1][0],scene.y+selected[1][1]);await delay(200);await drag(p,p.getByRole('slider',{name:'Individual flower height',exact:true}),.33);await drag(p,p.getByRole('slider',{name:'Individual flower size',exact:true}),1.25);await drag(p,p.getByRole('slider',{name:'Individual flower horizontal position',exact:true}),.2);await drag(p,p.getByRole('slider',{name:'Individual flower depth',exact:true}),.22);await click(p,button(p,'Show front view'),350);});
await shot('08',null,async p=>{await click(p,button(p,'Shuffle'),650);await click(p,button(p,'Undo'),550);await click(p,button(p,'Redo'),550);});
await shot('09',async p=>{await tab(p,'Objects').click();},async p=>{await click(p,button(p,'Add Cuddle Teddy'),300);await click(p,button(p,'Add Heart Balloon'),300);await click(p,button(p,'Edit Cuddle Teddy 1'),200);const points=await p.evaluate(()=>window.__petalpopObjectPoints());const c=await p.evaluate(()=>JSON.parse(localStorage.getItem('petalpop.draft.v1')));const a=points[c.objects[0].uid],box=await p.locator('.scene-wrap').boundingBox();await p.mouse.move(box.x+a[0],box.y+a[1]);await p.mouse.down();await p.mouse.move(box.x+a[0]-50,box.y+a[1]+6,{steps:18});await p.mouse.up();await delay(220);await drag(p,p.getByRole('slider',{name:'Object rotation',exact:true}),-18);await drag(p,p.getByRole('slider',{name:'Object size',exact:true}),.8);});
await shot('10',async p=>{await tab(p,'Objects').click();},async(p,mark)=>{await click(p,button(p,'Add Sealed Letter'),200);mark('open');await click(p,button(p,'Open & write a note'),0);await p.getByRole('textbox',{name:'Envelope note text',exact:true}).waitFor();mark('letter-revealed');const e=p.getByRole('textbox',{name:'Envelope note text',exact:true});await e.click();await e.pressSequentially("Happy birthday, Mia!\nHere's to more little adventures together.\nLove, Alex",{delay:12});await e.press('Control+A');await p.getByLabel('Note font',{exact:true}).selectOption('handwritten');await click(p,button(p,'Bold'),150);await click(p,button(p,'Save & seal'),350);});
await shot('11',async p=>{await tab(p,'Objects').click();},async(p,mark)=>{await click(p,button(p,'Add Memory Frame'),200);mark('upload');await p.getByLabel('Frame picture',{exact:true}).setInputFiles(path.join(demo,'public/assets/memory-photo.png'));await button(p,'Fill the frame').waitFor();await click(p,button(p,'Fill the frame'),180);await drag(p,p.getByRole('slider',{name:'Crop zoom',exact:true}),1.18,150);const canvas=p.getByRole('dialog',{name:'Crop frame picture',exact:true}).locator('canvas');const b=await canvas.boundingBox();await p.mouse.move(b.x+b.width/2,b.y+b.height/2);await p.mouse.down();await p.mouse.move(b.x+b.width/2-12,b.y+b.height/2+7,{steps:12});await p.mouse.up();await delay(180);await click(p,button(p,'Apply crop'),300);await click(p,button(p,'Landscape'),350);await drag(p,p.getByRole('slider',{name:'Object horizontal position',exact:true}),1.45);await drag(p,p.getByRole('slider',{name:'Object size',exact:true}),.86);});
await shot('12',async p=>{await tab(p,'Effects').click();},async(p,mark)=>{await click(p,button(p,'Select Confetti Pop'),0);mark('burst');await delay(2800);});
let giftUrl='';
await shot('13',async p=>{await tab(p,'Gift').click();},async(p,mark)=>{await p.getByLabel('For',{exact:true}).fill('Mia');await p.getByLabel('From',{exact:true}).fill('Alex');await p.getByLabel('Title',{exact:true}).fill('Happy birthday, Mia!');await p.getByLabel('Body',{exact:true}).fill('A little bouquet for your big day.');await delay(400);await click(p,button(p,'Share bouquet'),150);await button(p,'Copy link').waitFor({state:'visible'});await p.waitForFunction(()=>!document.querySelector('.share-actions .primary-button')?.disabled);giftUrl=await p.locator('.share-link').inputValue();await click(p,button(p,'Copy link'),550);mark('copied');});
if(requested){await json('output/capture-refinement-report.json',{requested,captures:captures.filter(c=>c.id===requested),errors});await browser.close();process.exit(0);}
// Get a saved gift and a genuine PNG without lengthening the demonstration with export work.
const exportContext=await browser.newContext({viewport:{width:1440,height:1040}});const ex=await exportContext.newPage();await init(ex,config);await ex.goto(url);await ready(ex);await button(ex,'Share bouquet').click();await ex.waitForFunction(()=>!document.querySelector('.share-actions .primary-button')?.disabled);giftUrl=await ex.locator('.share-link').inputValue();await ex.keyboard.press('Escape');const downloaded=ex.waitForEvent('download');await button(ex,'Save PNG').click();await (await downloaded).saveAs(path.join(demo,'public/assets/gift-card.png'));await exportContext.close();
await shot('14',async p=>{await p.evaluate(()=>import('/src/Viewer.tsx'));},async(p,mark)=>{await click(p,button(p,'Tap to open'),150);await button(p,'Keep this bouquet').waitFor();await p.waitForFunction(()=>!document.querySelector('.gift-bottom-actions .quiet-button')?.disabled);mark('gift-ready');await click(p,button(p,'Open your letter'),0);await p.getByRole('dialog',{name:'Read envelope note'}).locator('.note-reader').waitFor();mark('letter-revealed');await delay(400);},{giftUrl});
// Clean product views: actual recipient scenes with motion and the same saved gift.
for(const kind of ['hero','confetti','birthday','anniversary','thanks']){
if(requestedHeroes&&!requestedHeroes.includes(kind))continue;
const c=structuredClone(config);if(kind==='hero')c.effects=['hearts'];
const context=await browser.newContext({viewport:{width:1000,height:1050},recordVideo:{dir:path.join(demo,'recordings/raw'),size:{width:1000,height:1050}},reducedMotion:'no-preference'});const p=await context.newPage();await init(p,c);await p.goto(url);await phase(p,'#000000');await ready(p);
if(kind==='birthday'){await button(p,'Start with a preset').click();await p.getByRole('button',{name:/^Sunny side/}).click();}
if(kind==='anniversary'){await button(p,'Start with a preset').click();await p.getByRole('button',{name:/^Sweetheart/}).click();}
if(kind==='thanks'){await button(p,'Start with a preset').click();await p.getByRole('button',{name:/^Tiny thanks/}).click();}
await button(p,'Preview gift').click();await button(p,'Tap to open').click();await p.waitForFunction(()=>!document.querySelector('.gift-bottom-actions .quiet-button')?.disabled);await button(p,'Show front view').click();await delay(500);await p.locator('.gift-scene').scrollIntoViewIfNeeded();await p.addStyleTag({content:'.gift-scene .front-guide,.gift-scene .gift-scene-tools,#ad-pointer{visibility:hidden!important}'});const box=await p.locator('.gift-scene').boundingBox();await phase(p,'#FFFFFF');const begin=Date.now();if(kind==='confetti')await p.getByRole('button',{name:'Replay effects',exact:true,includeHidden:true}).evaluate(n=>n.click());await delay(kind==='confetti'?3050:6100);const end=Date.now();await phase(p,'#FF0000');await delay(400);await p.locator('.gift-scene').screenshot({path:path.join(demo,'public/assets',`${kind}.png`)});const extra=(Date.now()-end)/1000;const raw=p.video();await context.close();const source=await raw.path(),meta=await probe(source);const sync=await fence(source);const start=sync.start;const crop=`crop=${Math.floor(box.width/2)*2}:${Math.floor(box.height/2)*2}:${Math.round(box.x)}:${Math.round(box.y)},scale=1000:-2,fps=30,tpad=stop_mode=clone:stop_duration=2`;
await run(ffmpeg,['-y','-v','error','-i',source,'-vf',`trim=start=${start}:end=${sync.end},setpts=PTS-STARTPTS,`+crop,'-t',kind==='confetti'?'3':'6','-an','-c:v','libx264','-preset','fast','-crf','17','-pix_fmt','yuv420p',path.join(demo,'public/media',`${kind}.mp4`)]);console.log(`Captured clean ${kind}`);
}
await mkdir(path.join(demo,'public/assets/catalog'),{recursive:true});for(const folder of ['catalog','models'])for(const f of await readdir(path.join(root,'public',folder))){if(f.endsWith('.png'))await copyFile(path.join(root,'public',folder,f),path.join(demo,'public/assets/catalog',f));}
await json('output/recording-report.json',{recordedAt:new Date().toISOString(),app:url,viewport:[1440,1040],source:'Actual PetalPop React/Three.js app; isolated browser contexts and fictional gift',captures,errors,giftUrl,photo:'AI-generated fictional memory photo',nativeAnimations:['Flower additions','Flower sway','Envelope flight, seal, flap and paper','Confetti Pop','Gift reveal'],publication:false});
if(errors.length)throw new Error(`Browser errors: ${errors.join('; ')}`);
}finally{await browser.close();}
