import path from 'node:path';
import {readFile,writeFile,copyFile} from 'node:fs/promises';
import {demo} from './common.mjs';
const out=path.join(demo,'capcut-overlay-v2');
const plan=JSON.parse(await readFile(path.join(out,'rendered-moments.json'),'utf8'));
const csv=s=>'"'+String(s).replaceAll('"','""')+'"';
const rows=plan.moments.map(m=>[m.id,m.startFrame/30,(m.startFrame+m.durationFrames)/30,m.title,m.brief].map(csv).join(','));
await writeFile(path.join(out,'moment-sheet.csv'),'ID,Start seconds,End seconds,Subject,Graphic brief\n'+rows.join('\n')+'\n');
await copyFile(path.join(demo,'output/petalpop-marketing-ad.srt'),path.join(out,'petalpop-overlay-ad.srt'));
const buttons=plan.moments.map(m=>`<button data-at="${m.startFrame/30}"><b>${m.id.slice(-2)}</b> ${m.title}</button>`).join('');
await writeFile(path.join(out,'index.html'),`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>PetalPop 3D - Little blooms. Big feelings.</title><style>
*{box-sizing:border-box}body{margin:0;background:#FAF7F2;color:#493E46;font-family:'Trebuchet MS',sans-serif}main{max-width:1180px;margin:auto;padding:35px;display:grid;grid-template-columns:minmax(260px,460px) 1fr;gap:55px;align-items:start}video{width:100%;max-height:88vh;display:block;aspect-ratio:9/16;background:#F4E7EC;border-radius:20px;box-shadow:0 18px 50px #92576F1A}h1{font-size:46px;letter-spacing:-2px;margin:20px 0}h1 em{font-family:Georgia,serif;font-weight:400;color:#92576F}p{line-height:1.6;font-size:18px;color:#786671}.brand{color:#92576F;letter-spacing:2px;font-size:16px}.links{display:flex;gap:12px;flex-wrap:wrap;margin:24px 0}a{display:inline-block;border:1px solid #E0C9D4;color:#92576F;text-decoration:none;border-radius:12px;padding:12px 17px}a:first-child{background:#92576F;color:white}nav{display:grid;gap:6px;margin-top:18px}button{border:0;background:#F4E7EC;color:#493E46;padding:11px 14px;border-radius:10px;text-align:left;font:inherit;cursor:pointer}button:hover,button:focus-visible{background:#EBD5E0;outline:2px solid #92576F}button b{color:#92576F;margin-right:12px}small{color:#8D7B85}@media(max-width:760px){main{padding:18px;display:flex;flex-direction:column;gap:20px}section{width:100%}video{max-height:82vh}h1{font-size:37px;margin:12px 0}.links{margin:16px 0}nav{grid-template-columns:1fr}p{font-size:16px}}
</style></head><body><main><section><video controls playsinline preload="metadata" poster="poster.png" src="petalpop-overlay-ad.mp4"></video></section><section><div class="brand">PETALPOP 3D</div><h1>Little blooms.<br><em>Big feelings.</em></h1><p>A bouquet, a memory, and a little note from you. See a personal gift take shape, from the first flower to the final celebration.</p><div class="links"><a href="petalpop-overlay-ad.mp4" download>Download video</a><a href="petalpop-overlay-ad.srt" download>Captions</a></div><small>90 seconds · Tap a moment to jump in</small><nav aria-label="Video moments">${buttons}</nav></section></main><script>const v=document.querySelector('video');document.querySelectorAll('[data-at]').forEach(b=>b.addEventListener('click',()=>{v.currentTime=Number(b.dataset.at);v.play().catch(()=>{});}));</script></body></html>`);
console.log('Player, moment sheet and captions ready.');
